# Generated by Django 3.1.3 on 2023-07-22 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230722_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
